export const offlineFallback = {
  ecos: [
    { id:'eco-125', ecoNumber:'ECO-2026-00125', title:'Chemical Mixing Temperature Change', description:'Increase the chemical mixing operating temperature from 65°C to 70°C to improve process stability.', plant:'Plant 2', department:'Engineering', line:'Line 5', process:'Chemical Mixing', product:'Product A', risk:'High', status:'Training In Progress', confidence:94, created:'2026-09-10T08:10:00.000Z', owner:'Maya Chen', source:'Moji5 simulation', effectiveDate:'2026-09-15' },
    { id:'eco-126', ecoNumber:'ECO-2026-00126', title:'Torque specification update — Line 3', description:'Update fastener torque range for housing assembly.', plant:'Plant 2', department:'Engineering', line:'Line 3', process:'Housing Assembly', product:'Product A', risk:'Medium', status:'Impact Analysis Completed', confidence:81, created:'2026-09-09T10:10:00.000Z', owner:'Maya Chen', source:'Manual intake', effectiveDate:'2026-09-16' },
    { id:'eco-127', ecoNumber:'ECO-2026-00127', title:'Packaging label artwork revision', description:'Revise label artwork for new regulatory marking.', plant:'Plant 1', department:'Quality', line:'Line 2', process:'Final Packaging', product:'Product B', risk:'Low', status:'Awaiting Document Revision', confidence:76, created:'2026-09-08T10:10:00.000Z', owner:'Maya Chen', source:'Manual intake', effectiveDate:'2026-09-18' },
    { id:'eco-128', ecoNumber:'ECO-2026-00128', title:'CIP rinse cycle extension', description:'Extend rinse cycle to address residue observations.', plant:'Plant 3', department:'Operations', line:'Line 1', process:'Clean In Place', product:'Product C', risk:'Critical', status:'Approved', confidence:0, created:'2026-09-07T10:10:00.000Z', owner:'Maya Chen', source:'API', effectiveDate:'2026-09-20' }
  ], impacts: [], actions: [], training: [], audits: [
    { id:'AUD-001', ecoId:'eco-125', timestamp:'2026-09-10T08:10:00.000Z', event:'ECO received', source:'Moji5', user:'system', message:'ECO-2026-00125 received from source system', result:'Success' },
    { id:'AUD-002', ecoId:'eco-125', timestamp:'2026-09-10T08:11:00.000Z', event:'AI analysis complete', source:'LocalRuleBasedAIEngine', user:'system', message:'94% confidence · High impact · 8 downstream records', result:'Success' },
    { id:'AUD-003', ecoId:'eco-125', timestamp:'2026-09-10T08:12:00.000Z', event:'Training assignments generated', source:'TrainingEngine', user:'system', message:'47 employees identified; 47 local assignments created', result:'Success' }
  ], employees: Array.from({length:47},(_,i)=>`EMP${String(125+i).padStart(5,'0')} · ${['Ari Tan','Sam Lee','Nadia Lim','Jorge Santos','Rina Koh'][i%5]}`), health:{api:'Offline fallback',csv:'Bundled demo data',ai:'Healthy',workflow:'Healthy'}
};
